sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install -mod vendor golang.org/x/lint

script:
  - make check
  - make cover
